name: Save Player Roster

on:
  issues:
    types: [opened]

permissions:
  contents: write

jobs:
  save-roster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Markdown roster
        run: |
          crew_name=$(jq -r '.issue.title | capture("\

\[Roster\\]

: (?<val>.*)") | .val' $GITHUB_EVENT_PATH)
          campaign=$(jq -r '.issue.body | capture("Campaign\\s*\\n\\n(?<val>.*)\\n") | .val' $GITHUB_EVENT_PATH)
          origin=$(jq -r '.issue.body | capture("Zone Origin\\s*\\n\\n(?<val>.*)\\n") | .val' $GITHUB_EVENT_PATH)
          edge=$(jq -r '.issue.body | capture("Edge\\s*\\n\\n(?<val>.*)\\n") | .val' $GITHUB_EVENT_PATH)
          agenda=$(jq -r '.issue.body | capture("Secondary Agenda.*\\n\\n(?<val>.*)\\n") | .val' $GITHUB_EVENT_PATH)

          outdir="campaigns/${campaign}"
          mkdir -p "$outdir"
          outfile="${outdir}/${crew_name// /-}-roster.md"

          {
            echo "# 📋 Zone Roster: ${crew_name}"
            echo
            echo "**Campaign:** ${campaign}  "
            echo "**Origin:** ${origin}  "
            echo "**Edge:** ${edge}  "
            echo "**Secondary Agenda:** ${agenda}"
            echo
            echo "---"
            echo
            echo "## 👥 Crew Members"
            echo
            echo "| # | Role | Weapon | Equipment |"
            echo "|---|------|--------|-----------|"

            # (loop through crew members here, as in your script)
          } > "$outfile"

      - name: Commit roster file
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add campaigns/
          git commit -m "Add roster for ${crew_name}" || echo "No changes to commit"
          git push
