name: Build a Zone Roster
description: Guided form to create your crew roster
title: "[Roster]: <Crew Name>"
labels: ["roster"]

body:
  - type: input
    id: crew-name
    attributes:
      label: Crew Name
      placeholder: e.g. "The Iron Dogs"
    validations:
      required: true

  - type: dropdown
    id: campaign
    attributes:
      label: Campaign
      options:
        - CordonRun
        - DeadCity
        - RedForest
    validations:
      required: true

  - type: dropdown
    id: origin
    attributes:
      label: Zone Origin
      options: {{origins}}
    validations:
      required: true

  - type: dropdown
    id: edge
    attributes:
      label: Edge
      options: {{edges}}
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## 👥 Crew Members"

  # Crew Members (8 total, each with Role + Weapon)
  - type: dropdown
    id: crew-role-1
    attributes:
      label: Crew Member 1 Role
      options: {{roles}}
    validations:
      required: true
  - type: dropdown
    id: weapon-1
    attributes:
      label: Crew Member 1 Weapon
      options: {{weapons}}
    validations:
      required: true

  - type: dropdown
    id: crew-role-2
    attributes:
      label: Crew Member 2 Role
      options: {{roles}}
    validations:
      required: true
  - type: dropdown
    id: weapon-2
    attributes:
      label: Crew Member 2 Weapon
      options: {{weapons}}
    validations:
      required: true

  # …repeat Role + Weapon for Crew Members 3–8

  - type: markdown
    attributes:
      value: "## 🎒 Shared Equipment Pool (3 total for the whole crew)"

  # Equipment Slot 1
  - type: dropdown
    id: equipment-1
    attributes:
      label: Equipment Slot 1
      options: {{equipment}}
    validations:
      required: false
  - type: dropdown
    id: equipment-1-owner
    attributes:
      label: Who carries Equipment Slot 1?
      options:
        - Crew Member 1
        - Crew Member 2
        - Crew Member 3
        - Crew Member 4
        - Crew Member 5
        - Crew Member 6
        - Crew Member 7
        - Crew Member 8
    validations:
      required: false

  # Equipment Slot 2
  - type: dropdown
    id: equipment-2
    attributes:
      label: Equipment Slot 2
      options: {{equipment}}
    validations:
      required: false
  - type: dropdown
    id: equipment-2-owner
    attributes:
      label: Who carries Equipment Slot 2?
      options:
        - Crew Member 1
        - Crew Member 2
        - Crew Member 3
        - Crew Member 4
        - Crew Member 5
        - Crew Member 6
        - Crew Member 7
        - Crew Member 8
    validations:
      required: false

  # Equipment Slot 3
  - type: dropdown
    id: equipment-3
    attributes:
      label: Equipment Slot 3
      options: {{equipment}}
    validations:
      required: false
  - type: dropdown
    id: equipment-3-owner
    attributes:
      label: Who carries Equipment Slot 3?
      options:
        - Crew Member 1
        - Crew Member 2
        - Crew Member 3
        - Crew Member 4
        - Crew Member 5
        - Crew Member 6
        - Crew Member 7
        - Crew Member 8
    validations:
      required: false
