name: Build a Zone Roster
description: Guided form to create your crew roster
title: "[Roster]: <Crew Name>"
labels: ["roster"]
body:
  - type: input
    id: crew-name
    attributes:
      label: Crew Name
      placeholder: e.g. "The Iron Dogs"
    validations:
      required: true

  - type: dropdown
    id: origin
    attributes:
      label: Zone Origin
      options: {{origins}}
    validations:
      required: true

  - type: dropdown
    id: edge
    attributes:
      label: Edge
      options:
        - SEVA Brigade
        - Artifact Attunement
        - Psy Resonance
        - Telekinetic Drift
        - Synthetic Bodies
        - War-Born
        - Linked Comms
        - Camaraderie
        - Brutal Pragmatists
        - Smuggler Network
        - Mimics of the Zone
        - Time Anomalies
        - Chem-Dosed
        - Parasitic Takeover
    validations:
      required: true

  # Crew slots (8 max, each with Role + Gear)
  - type: dropdown
    id: crew-role-1
    attributes:
      label: Crew Member 1 Role
      options: {{roles}}
    validations:
      required: true
  - type: dropdown
    id: gear-1
    attributes:
      label: Gear for Crew Member 1
      options: {{gear}}
    validations:
      required: true

  - type: dropdown
    id: crew-role-2
    attributes:
      label: Crew Member 2 Role
      options: {{roles}}
    validations:
      required: true
  - type: dropdown
    id: gear-2
    attributes:
      label: Gear for Crew Member 2
      options: {{gear}}
    validations:
      required: true

  - type: dropdown
    id: crew-role-3
    attributes:
      label: Crew Member 3 Role
      options: {{roles}}
    validations:
      required: true
  - type: dropdown
    id: gear-3
    attributes:
      label: Gear for Crew Member 3
      options: {{gear}}
    validations:
      required: true

  - type: dropdown
    id: crew-role-4
    attributes:
      label: Crew Member 4 Role
      options: {{roles}}
    validations:
      required: true
  - type: dropdown
    id: gear-4
    attributes:
      label: Gear for Crew Member 4
      options: {{gear}}
    validations:
      required: true

  - type: dropdown
    id: crew-role-5
    attributes:
      label: Crew Member 5 Role
      options: {{roles}}
    validations:
      required: true
  - type: dropdown
    id: gear-5
    attributes:
      label: Gear for Crew Member 5
      options: {{gear}}
    validations:
      required: true

  - type: dropdown
    id: crew-role-6
    attributes:
      label: Crew Member 6 Role
      options: {{roles}}
    validations:
      required: true
  - type: dropdown
    id: gear-6
    attributes:
      label: Gear for Crew Member 6
      options: {{gear}}
    validations:
      required: true

  - type: dropdown
    id: crew-role-7
    attributes:
      label: Crew Member 7 Role
      options: {{roles}}
    validations:
      required: true
  - type: dropdown
    id: gear-7
    attributes:
      label: Gear for Crew Member 7
      options: {{gear}}
    validations:
      required: true

  - type: dropdown
    id: crew-role-8
    attributes:
      label: Crew Member 8 Role
      options: {{roles}}
    validations:
      required: true
  - type: dropdown
    id: gear-8
    attributes:
      label: Gear for Crew Member 8
      options: {{gear}}
    validations:
      required: true

  - type: dropdown
    id: secondary-agenda
    attributes:
      label: Secondary Agenda (Optional)
      options:
        - Rescue
        - Artifact (Tech)
        - Biology
        - Intel (Data)
        - Armaments
        - Medicine
