name: Build Dynamic Roster Form

on:
  push:
    paths:
      - .github/roster-config.yml
      - .github/ISSUE_TEMPLATE/_roster-template.yml
  workflow_dispatch:

jobs:
  build-form:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq yq

      - name: Generate roster.yml
        run: |
          # Parse origins from config
          origins=$(yq -o=json '.origins | keys' .github/roster-config.yml | jq -r '.[]' | sed 's/^/  - /')
          
          # For now, just flatten roles/gear for all origins (you can refine per-origin later)
          roles=$(yq -o=json '.origins[].roles[]' .github/roster-config.yml | sort -u | jq -r '.' | sed 's/^/  - /')
          gear=$(yq -o=json '.origins[].gear[]' .github/roster-config.yml | sort -u | jq -r '.' | sed 's/^/  - /')

          # Replace placeholders in template
          sed -e "/{{origins}}/{
            r /dev/stdin
            d
          }" <(echo "$origins") .github/ISSUE_TEMPLATE/_roster-template.yml \
          | sed -e "/{{roles}}/{
            r /dev/stdin
            d
          }" <(echo "$roles") \
          | sed -e "/{{gear}}/{
            r /dev/stdin
            d
          }" <(echo "$gear") \
          > .github/ISSUE_TEMPLATE/roster.yml

      - name: Commit updated form
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .github/ISSUE_TEMPLATE/roster.yml
          git commit -m "Update roster form with dynamic dropdowns" || echo "No changes to commit"
          git push
