name: Build Dynamic Roster Form

on:
  push:
    paths:
      - .github/roster-config.yml
      - .github/ISSUE_TEMPLATE/_roster-template.yml
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-form:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install yq (Go-based)
        run: |
          wget https://github.com/mikefarah/yq/releases/download/v4.44.1/yq_linux_amd64 -O /usr/bin/yq
          chmod +x /usr/bin/yq

      - name: Generate roster.yml
        run: |
          # Extract origins, roles, gear
          origins=$(yq '.origins | keys' -o=json .github/roster-config.yml | jq -r '.[]' | sed 's/^/  - /')
          roles=$(yq '.origins[].roles[]' -o=json .github/roster-config.yml | jq -r '.' | sort -u | sed 's/^/  - /')
          gear=$(yq '.origins[].gear[]' -o=json .github/roster-config.yml | jq -r '.' | sort -u | sed 's/^/  - /')

          # Replace placeholders in template with arrays
          sed "/{{origins}}/ {
              r /dev/stdin
              d
          }" <(echo "$origins") .github/ISSUE_TEMPLATE/_roster-template.yml \
          | sed "/{{roles}}/ {
              r /dev/stdin
              d
          }" <(echo "$roles") \
          | sed "/{{gear}}/ {
              r /dev/stdin
              d
          }" <(echo "$gear") \
          > .github/ISSUE_TEMPLATE/roster.yml

      - name: Commit updated form
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .github/ISSUE_TEMPLATE/roster.yml
          git commit -m "Update roster form with dynamic dropdowns" || echo "No changes to commit"
          git pull --rebase origin main
          git push
