name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches: [ main ]   # or your default branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Publish Blazor WASM
        run: dotnet publish ZoneRosterBuilder/ZoneRosterBuilder/ZoneRosterBuilder.csproj -c Release -o release
      
      - name: Add SPA fallback
        run: cp release/wwwroot/index.html release/wwwroot/404.html
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./release/wwwroot
          publish_branch: gh-pages

